version: '3.0'
services:
  kafka:
    container_name: kafka
    hostname: kafka
    image: apache/kafka:3.7.0
    ports:
      - '9092:9092'
#
#  kafdrop:
#    container_name: kafdrop
#    image: obsidiandynamics/kafdrop
#    ports:
#      - '9000:9000'
#    environment:
#      KAFKA_BROKERCONNECT: 'kafka:9092'
#    depends_on:
#      - 'kafka'
